"""Council-of-5 backtested weather verdict system.

A panel of five independent, top-band national weather centers each cast a
data-derived vote on a city's daily high/low. A chair reconciles the votes
into a skill-weighted verdict whose accuracy is proven on held-out history.

No temperature value in this system is generated by a language model. Every
figure traces to an API call; every weight is computed from backtested error.
"""

__version__ = "1.0.0"
